{
    'name': 'Email Purchase confirmed',
    'version': '14.0',
    'summary': 'Email Purchase confirmed',
    'description': 'Email Purchase confirmed',
    'category': 'sales',
    'author': 'Meyrina Herawati',
    'website': 'rexmey.com',
    'license': '',
    'depends': ['purchase'],
    'data': ['views/mail_template.xml'],
    # 'demo': [''],
    'installable': True,
    'auto_install': False,
}